### ISSUE TITLE
'Platform/BHAssert.h' file not found

### ISSUE THREAD

**Issue by simon-camp** [bhuman/CompiledNN#2]
I'm trying to add a new target with an example usage of this library to the cmake file. Linking against the CompiledNN library yields this error though.

If I understand the cmake stuff correctly, this is because the B-Human subdirectory is included as PRIVATE. So targets depending on CompiledNN don't transitively include the files as well.

To fix this, I think, one has to either include the B-Human subdirectory as PUBLIC or remove the uses from the public headers of CompiledNN.

**Comment by bhuman** [comment]
This is correct, I changed this already locally a few days ago and will push it in ~1h.

**Comment by ahasselbring** [comment]
Fixed by 45967f567639475d2d6e8cbb259fa56dfa22b7e0
