### ISSUE TITLE
ASSERT(input.dims(2) <= settings.xmmRegs() * 4) failed

### ISSUE THREAD

**Issue by b4rthm** [bhuman/CompiledNN#5]
Hello,

I'm trying to compile a simple model
```
inputs = Input((120,160,1))
conv1 = Conv2D(64, 3, activation = 'relu', padding = 'same')(inputs)
pool1 = MaxPooling2D(pool_size=(2, 2))(conv1)
conv2 = Conv2D(128, 3, activation = 'relu', padding = 'same')(pool1)
up1 = UpSampling2D(size = (2,2))(conv2)
merge = Concatenate()([up1,conv1]                 )
conv3 = Conv2D(64, 3, activation = 'relu', padding = 'same')(merge)
outputs = Conv2D(64, (1,1))(conv3)

model = Model(input = inputs, output = outputs) 
```
but I get the following error, which i don't fully understand.

/home/barth/Workspace/CompiledNN/Src/CompiledNN/CompiledNN/Operations/UpSampling2D.cpp:25: ASSERT(input.dims(2) <= settings.xmmRegs() * 4) failed
Aborted (core dumped)

**Comment by ahasselbring** [comment]
Hi,
the current implementation of the `Upsampling2D` layer requires that all channels of a single pixel fit into the SSE registers, which amounts to a limit of 32 channels on 32-bit CPUs and 64 channels on 64-bit CPUs.

**Comment by b4rthm** [comment]
thanks, that solved the Problem.
